-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeT9MHOTJhNM76lXQ
CgKo3qgV8sRnQYs25g/UuqOfmj+gCgYIKoZIzj0DAQehRANCAATwxLNLIxa/qg+s
hcoHmLHpEkVqwNsB9b9pltZNk5IDrxn5CJLu+6Cijc3E+GmZMNRg73piwrL1dPqQ
D+25NbXo
-----END PRIVATE KEY-----